### ISSUE TITLE
1.8.8 Support

### ISSUE THREAD

**Issue by siobhan-saoirse** [DirtPowered/Release2Beta#1]
Will there be 1.8.8 support for this plugin? (question)

**Comment by Saraistupid** [comment]
answering instead of the dev (since i asked him before), he told me no, it won't be implemented cuz of problems with MCProtocoLib 1.8

**Comment by siobhan-saoirse** [comment]
Thanks!

**Comment by Saraistupid** [comment]
np, i guess

**Comment by Saraistupid** [comment]
i actually recommend joining the discord

**Comment by siobhan-saoirse** [comment]
I already did. as ICS
